---
galaxy_info:
  author: Ben Crisp
  description: Generate Systemd units
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - systemd
dependencies: []
