---
- name: >-
    ensure that the systemd dropin directory {{ systemd_dropin_unit_user_dir 
    if dropin.user_unit|default(False) 
    else systemd_dropin_unit_system_dir }}/{{ dropin.unit }}.d is in the correct state
  ansible.builtin.file:
    state: directory
    path: >-
      "{{ systemd_dropin_unit_user_dir if dropin.user_unit|default(False)
      else systemd_dropin_unit_system_dir }}/{{ dropin.unit }}.d"
    owner: "{{ dropin.dir_owner|default(systemd_dropin_dir_owner) }}"
    group: "{{ dropin.dir_group|default(systemd_dropin_dir_group) }}"
    mode: "{{ dropin.dir_mode|default(systemd_dropin_dir_mode) }}"

- name: >-
    ensure that the systemd dropin file {{ dropin.name }}.conf for unit
    {{ dropin.unit }} is in the correct state
  import_role:
    name: bcrisp4.systemd.file
  vars:
    systemd_files:
      - path: >-
          {{ systemd_dropin_unit_user_dir if dropin.user_unit|default(False)
          else systemd_dropin_unit_system_dir }}/{{ dropin.unit }}.d/{{ dropin.name }}.conf
        owner: "{{ dropin.owner|default(systemd_dropin_file_owner) }}"
        group: "{{ dropin.group|default(systemd_dropin_file_group) }}"
        mode: "{{ dropin.mode|default(systemd_dropin_file_mode) }}"
        sections: "{{ dropin.sections }}"
        handlers:
          - reload systemd
  when: dropin.sections is defined
