---
galaxy_info:
  author: Ben Crisp
  description: Manage dropin files for systemd units
  license: GPL-2.0-or-later
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - systemd
dependencies: []
