name: "bcrisp4.systemd.file"
on:
  workflow_dispatch: {}
  push:
    paths:
      - 'roles/file/**'
      - 'molecule/file/**'
      - '.github/workflows/file.yml'
  pull_request:
    paths:
      - 'roles/file/**'
      - 'molecule/file/**'
      - '.github/workflows/file.yml'
jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: true
      matrix:
        test_distro:
          - distro: debian:10
        role_name:
          - file
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/bcrisp4/systemd

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: ansible_collections/bcrisp4/systemd
        run: |
          sudo apt install docker
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Test role
        run: >-
          molecule --version &&
          ansible --version &&
          TEST_DISTRO=${{ matrix.test_distro.distro }}
          molecule test -s ${{ matrix.role_name }}
